/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ClientType = {
    Web: 'web',
    Desktop: 'desktop',
    Mobile: 'mobile'
} as const;
export type ClientType = typeof ClientType[keyof typeof ClientType];


export function instanceOfClientType(value: any): boolean {
    for (const key in ClientType) {
        if (Object.prototype.hasOwnProperty.call(ClientType, key)) {
            if (ClientType[key as keyof typeof ClientType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ClientTypeFromJSON(json: any): ClientType {
    return ClientTypeFromJSONTyped(json, false);
}

export function ClientTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientType {
    return json as ClientType;
}

export function ClientTypeToJSON(value?: ClientType | null): any {
    return value as any;
}

export function ClientTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ClientType {
    return value as ClientType;
}

