/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUser
 */
export interface CreateUser {
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    uuid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    language?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    timezone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    ipAddress?: string | null;
}

/**
 * Check if a given object implements the CreateUser interface.
 */
export function instanceOfCreateUser(value: object): value is CreateUser {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateUserFromJSON(json: any): CreateUser {
    return CreateUserFromJSONTyped(json, false);
}

export function CreateUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUser {
    if (json == null) {
        return json;
    }
    return {
        
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'name': json['name'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'language': json['language'] == null ? undefined : json['language'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'ipAddress': json['ip_address'] == null ? undefined : json['ip_address'],
    };
}

export function CreateUserToJSON(json: any): CreateUser {
    return CreateUserToJSONTyped(json, false);
}

export function CreateUserToJSONTyped(value?: CreateUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uuid': value['uuid'],
        'name': value['name'],
        'display_name': value['displayName'],
        'email': value['email'],
        'password': value['password'],
        'language': value['language'],
        'timezone': value['timezone'],
        'currency': value['currency'],
        'ip_address': value['ipAddress'],
    };
}

