/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.4.2
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdentityProviderType } from './IdentityProviderType';
import {
    IdentityProviderTypeFromJSON,
    IdentityProviderTypeFromJSONTyped,
    IdentityProviderTypeToJSON,
    IdentityProviderTypeToJSONTyped,
} from './IdentityProviderType';

/**
 * 
 * @export
 * @interface ExternalAccount
 */
export interface ExternalAccount {
    /**
     * 
     * @type {string}
     * @memberof ExternalAccount
     */
    userId?: string;
    /**
     * 
     * @type {IdentityProviderType}
     * @memberof ExternalAccount
     */
    provider: IdentityProviderType;
    /**
     * 
     * @type {string}
     * @memberof ExternalAccount
     */
    externalId: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExternalAccount
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ExternalAccount
     */
    authorized?: boolean;
    /**
     * 
     * @type {{ [key: string]: any | null; }}
     * @memberof ExternalAccount
     */
    fields?: { [key: string]: any | null; } | null;
    /**
     * 
     * @type {Date}
     * @memberof ExternalAccount
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ExternalAccount
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ExternalAccount
     */
    deletedAt?: Date | null;
}



/**
 * Check if a given object implements the ExternalAccount interface.
 */
export function instanceOfExternalAccount(value: object): value is ExternalAccount {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('externalId' in value) || value['externalId'] === undefined) return false;
    return true;
}

export function ExternalAccountFromJSON(json: any): ExternalAccount {
    return ExternalAccountFromJSONTyped(json, false);
}

export function ExternalAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'provider': IdentityProviderTypeFromJSON(json['provider']),
        'externalId': json['external_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'authorized': json['authorized'] == null ? undefined : json['authorized'],
        'fields': json['fields'] == null ? undefined : json['fields'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'deletedAt': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
    };
}

export function ExternalAccountToJSON(json: any): ExternalAccount {
    return ExternalAccountToJSONTyped(json, false);
}

export function ExternalAccountToJSONTyped(value?: ExternalAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'provider': IdentityProviderTypeToJSON(value['provider']),
        'external_id': value['externalId'],
        'name': value['name'],
        'authorized': value['authorized'],
        'fields': value['fields'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
        'deleted_at': value['deletedAt'] == null ? undefined : ((value['deletedAt'] as any).toISOString()),
    };
}

