/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GameServerStatus = {
    Unknown: 'unknown',
    Offline: 'offline',
    Online: 'online'
} as const;
export type GameServerStatus = typeof GameServerStatus[keyof typeof GameServerStatus];


export function instanceOfGameServerStatus(value: any): boolean {
    for (const key in GameServerStatus) {
        if (Object.prototype.hasOwnProperty.call(GameServerStatus, key)) {
            if (GameServerStatus[key as keyof typeof GameServerStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GameServerStatusFromJSON(json: any): GameServerStatus {
    return GameServerStatusFromJSONTyped(json, false);
}

export function GameServerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameServerStatus {
    return json as GameServerStatus;
}

export function GameServerStatusToJSON(value?: GameServerStatus | null): any {
    return value as any;
}

export function GameServerStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): GameServerStatus {
    return value as GameServerStatus;
}

