/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.4.2
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const IdentityProviderType = {
    Steam: 'steam',
    Epic: 'epic',
    Discord: 'discord',
    Microsoft: 'microsoft',
    Playstation: 'playstation',
    Google: 'google',
    Apple: 'apple'
} as const;
export type IdentityProviderType = typeof IdentityProviderType[keyof typeof IdentityProviderType];


export function instanceOfIdentityProviderType(value: any): boolean {
    for (const key in IdentityProviderType) {
        if (Object.prototype.hasOwnProperty.call(IdentityProviderType, key)) {
            if (IdentityProviderType[key as keyof typeof IdentityProviderType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IdentityProviderTypeFromJSON(json: any): IdentityProviderType {
    return IdentityProviderTypeFromJSONTyped(json, false);
}

export function IdentityProviderTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityProviderType {
    return json as IdentityProviderType;
}

export function IdentityProviderTypeToJSON(value?: IdentityProviderType | null): any {
    return value as any;
}

export function IdentityProviderTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): IdentityProviderType {
    return value as IdentityProviderType;
}

