/* tslint:disable */
/* eslint-disable */
/**
 * Tribufu API
 * API to access Tribufu services.
 *
 * The version of the OpenAPI document: 1.4.2
 * Contact: contact@tribufu.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Profile
 */
export interface Profile {
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    readonly name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    readonly displayName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    readonly level?: number;
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    readonly experience?: number;
    /**
     * 
     * @type {Date}
     * @memberof Profile
     */
    readonly birthday?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof Profile
     */
    readonly points?: number;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    readonly photoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    readonly bannerUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Profile
     */
    readonly lastOnline?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Profile
     */
    readonly biography?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Profile
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Profile
     */
    readonly updatedAt?: Date | null;
}

/**
 * Check if a given object implements the Profile interface.
 */
export function instanceOfProfile(value: object): value is Profile {
    return true;
}

export function ProfileFromJSON(json: any): Profile {
    return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'level': json['level'] == null ? undefined : json['level'],
        'experience': json['experience'] == null ? undefined : json['experience'],
        'birthday': json['birthday'] == null ? undefined : (new Date(json['birthday'])),
        'points': json['points'] == null ? undefined : json['points'],
        'photoUrl': json['photo_url'] == null ? undefined : json['photo_url'],
        'bannerUrl': json['banner_url'] == null ? undefined : json['banner_url'],
        'lastOnline': json['last_online'] == null ? undefined : (new Date(json['last_online'])),
        'biography': json['biography'] == null ? undefined : json['biography'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function ProfileToJSON(json: any): Profile {
    return ProfileToJSONTyped(json, false);
}

export function ProfileToJSONTyped(value?: Omit<Profile, 'id'|'name'|'display_name'|'level'|'experience'|'birthday'|'points'|'photo_url'|'banner_url'|'last_online'|'biography'|'created_at'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

